### ISSUE TITLE
Send the `props` object to the domElementGetter function

### ISSUE THREAD

**Issue by andrefrua** [single-spa/single-spa-angularjs#44]
Hello,
Would be it possible to make a change here:

https://github.com/single-spa/single-spa-angularjs/blob/931d108022e00fdfa0bea55220dd267141ce1687/src/single-spa-angularjs.js#L109

So that the domElementGetter receive the props?

A similar change was made for the react version here:
https://github.com/single-spa/single-spa-react/issues/71

Thank you

**Comment by joeldenning** [comment]
Hi @andrefrua, sure I'm open to that change. Here is the relevant line of code:

https://github.com/single-spa/single-spa-angularjs/blob/931d108022e00fdfa0bea55220dd267141ce1687/src/single-spa-angularjs.js#L109

Could you submit a pull request to add this?

**Comment by andrefrua** [comment]
Sure :)
Here it is:
https://github.com/single-spa/single-spa-angularjs/pull/45

**Comment by joeldenning** [comment]
Thanks! This is released in https://github.com/single-spa/single-spa-angularjs/releases/tag/v3.3.0.

Could you send a pull request to update the documentation for this? You can modify it at https://github.com/single-spa/single-spa.js.org/edit/master/website/versioned_docs/version-5.x/ecosystem-angularjs.md

**Comment by andrefrua** [comment]
Here it is: https://github.com/single-spa/single-spa.js.org/pull/254

Let me know if it's ok :)

**Comment by joeldenning** [comment]
👍 looks great, thanks. Closing this issue.
