### ISSUE TITLE
$rootScope not working in singleSpaAngularJS

### ISSUE THREAD

**Issue by ajaykumarsana** [single-spa/single-spa-angularjs#48]
Hi @joeldenning  @nicholas-johnson ,

I'm using **singleSpaAngularJS** for my AngularJS project, was able to load application but **$rootScope** features not working.

- $rootScope.someVariable = 'Hello';

above variable not accessible in application. 

- `$rootScope.$on('$stateChangeSuccess', function() {});`
above function block not getting executed

Can you please help?

**Comment by joeldenning** [comment]
I don't think that this is related to single-spa-angularjs. I have used $rootScope in single-spa-angularjs projects successfully for a long time. Could you share a demonstration of the problem?
