### ISSUE TITLE
Angular not picking up singleSpaProps on initial render

### ISSUE THREAD

**Issue by patelrikin** [single-spa/single-spa-angularjs#51]
My dummy controller looks like following:

```
import angularModule from '../rootFolder';

angularModule.component('root', {
  template: require('./home.template.html'),
  controller: [
    '$scope',
    '$rootScope',
    function ($scope, $rootScope) {
      // This does not work during initial render of the application
      $scope.customProps = $rootScope.singleSpaProps;

      // This one works because it watches for the property on the $rootScope
      $rootScope.$watch('singleSpaProps', function () {
        $scope.customProps = $rootScope.singleSpaProps;
      });
    },
  ],
});

```
My question is whenever `singleSpaProps` is injected or added on the `$rootScope` should it also trigger `$digest ` cycle so that consuming AngularJS app picks up newly added property?

I am using following setup to expose and register the app as singleSpa

```
const lifecycles = singleSpaAngularJS({
  angular,
  mainAngularModule: 'angularjs-app',
  uiRouter: false,
  preserveGlobal: false,
  template: '<root />',
});

export const { bootstrap, mount, unmount } = lifecycles;
```

I see that https://github.com/single-spa/single-spa-angularjs/issues/42 tried to resolve it with issue from https://github.com/single-spa/single-spa-angularjs/issues/41.

**Comment by joeldenning** [comment]
Hi @patelrikin, thanks for the clear description. I don't know of a way to add the props to the rootScope during the initial render, since `angular.bootstrap()` doesn't seem to accept any kind of data ([explanation](https://docs.angularjs.org/api/ng/function/angular.bootstrap)). I doubt that calling `$rootScope.$digest()` will change the initial render. However, if it does I am very open to the change. Could you test it out and submit a pull request with the change, if it indeed fixes the problem?

**Comment by patelrikin** [comment]
> Hi @patelrikin, thanks for the clear description. I don't know of a way to add the props to the rootScope during the initial render, since `angular.bootstrap()` doesn't seem to accept any kind of data ([angularjs docs](https://docs.angularjs.org/api/ng/function/angular.bootstrap)). I doubt that calling `$rootScope.$digest()` will change the initial render. However, if it does I am very open to the change. Could you test it out and submit a pull request with the change, if it indeed fixes the problem?

@joeldenning Thank you for responding. I will try this over the weekend and find out if it resolves or not.

**Comment by patelrikin** [comment]
I attempted to try using several methods available on `$rootScope` and apparently it did not work well. 
I tried using `$timeOut`, `$digest` and `$evalAsync` but all resulted in not reflecting `singleSpaProps` being recognized in my AngularJS component. I am not sure of `$evalAsync` usage so I'm not sure if I tried it proper way which could also be an issue.

At this point I'm not sure what the fix would be at this point, and would have to delegate this to other experts who knows AngularJS better.

**Comment by joeldenning** [comment]
Here's the link to the angularjs `bootstrap()` function:

https://github.com/angular/angular.js/blob/2e72ea13fa98bebf6ed4b5e3c45eaf5f990ed16f/src/Angular.js#L1793

And here's the code that creates a root scope object:

https://github.com/angular/angular.js/blob/26a5779cddf70944b7548e3a6410d35237a516e5/src/ng/rootScope.js#L175

I don't immediately see anything that lets you set initial values on the root scope.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-angularjs/releases/tag/v4.2.3
