### ISSUE TITLE
UI-router prevents navigation to other apps

### ISSUE THREAD

**Issue by klaimmore** [single-spa/single-spa-angularjs#53]
If an angularjs app with ui-router defines default urls with [$urlRouterProvider.otherwise('/default');](https://github.com/angular-ui/ui-router/wiki/URL-Routing#otherwise-for-invalid-routes)
Then navigating away from that app is no longer possible.

I uploaded an example of the issue [here](https://github.com/klaimmore/angularjs-uirouter-microfrontend)

Navigating from app1 to app2 is possible, but not the other way around.

I added a custom unmount function that resolve the issue when using ui-router>1. By calling [dispose()](https://ui-router.github.io/core/docs/latest/interfaces/_interface_.disposable.html#dispose) on the `$uiRouter` instance:

```
angular.element(document.getElementById('main')).children('.ng-scope').injector().get('$uiRouter').dispose();
```

But it relies on locating the app's injector.

**Comment by joeldenning** [comment]
Thanks for creating the demonstration repo, and for investigating a fix. I created https://github.com/klaimmore/angularjs-uirouter-microfrontend/pull/1 which uses a modified version of single-spa-angularjs that fixes it for both app1 and app2.

I'll also put together a PR to single-spa-angularjs with the fix so we can get it merged and published.

**Comment by joeldenning** [comment]
I've created https://github.com/single-spa/single-spa-angularjs/pull/54 which implements this fix.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-angularjs/releases/tag/v4.1.0
