### ISSUE TITLE
No support for ngRoute in singla-spa-angularjs

### ISSUE THREAD

**Issue by roanjain** [single-spa/single-spa-angularjs#62]
My angularjs app is not using ui-router but ngRoute, I couldn't find the support for it.

**Comment by joeldenning** [comment]
I think the single-spa-angularjs works with ngRoute, but haven't tried it. I don't know of any special logic required for ngRoute to work.

Is something not working for you when you use ngRoute? If so, I can take a look to fix it if you provide a demonstration repo.

**Comment by roanjain** [comment]
I created a PR for the same and able to make it work with the fix given in PR, but still, there is one issue pending i.e., I am not able to move away from angularjs app to any other app. Looks similar to https://github.com/single-spa/single-spa-angularjs/issues/53

https://github.com/single-spa/single-spa-angularjs/pull/63/commits/b001c5fef26db11cd23e91992920a3440ea9b728

**Comment by roanjain** [comment]
The fix given in the below commit made the other issue work as well but requires a change in angular.js. Not sure if there could be a better way to handle it from outside. https://github.com/netman92/angular.js/commit/3ee26531c810f8ac5b66ab29a48712f9638a7bf8

**Comment by joeldenning** [comment]
Published in https://github.com/single-spa/single-spa-angularjs/releases/tag/v4.3.1 and documented in https://github.com/single-spa/single-spa.js.org/pull/451

**Comment by joeldenning** [comment]
> The fix given in the below commit made the other issue work as well but requires a change in angular.js. Not sure if there could be a better way to handle it from outside. netman92/angular.js@3ee2653

It seems that https://github.com/netman92/angular.js/commit/3ee26531c810f8ac5b66ab29a48712f9638a7bf8 was merged into the main angularjs repo now and is there in the latest versions? I am looking at 
 https://github.com/angular/angular.js/blob/e29900c78f8fa962559b1cf95e1e7d428230e645/src/ng/browser.js#L258 and https://github.com/angular/angular.js/blob/e29900c78f8fa962559b1cf95e1e7d428230e645/src/ng/rootScope.js#L1030 and see the code from your fork is also in the upstream angularjs repo.

Are you talking about older versions of angularjs that do not have that fix yet? Or is there something I'm missing
