### ISSUE TITLE
Controller runs multiple times after remount

### ISSUE THREAD

**Issue by byron-paystack** [single-spa/single-spa-angularjs#64]
Hi,

As per the title I am currently running an Angular and a React application on separate routes as part of a migration strategy.
Once the angular app has been unmounted and then remounted all subsequent routing events run the controller for the module several times. It is an exponential effect as after the third route change we have controllers from previous routes rerunning in the new routes into the 100's. It seems to be an issue with single-spa because the app runs perfectly fine by itself and the config object is minimal.

**Comment by joeldenning** [comment]
Could you provide a demonstration of the issue, perhaps as a github repository or code sandbox? It might depend on your version of angular, angular-ui-router, single-spa-angularjs, etc.

**Comment by byron-paystack** [comment]
@joeldenning thanks for the assist. The app is confidential IP however we are looking into the issue and I will create a stripped down playground if nothing surfaces. It may be a unique blend of our packages. Give me a couple of days.
