### ISSUE TITLE
looking for router based app with angularjs 1.5x, angular and react

### ISSUE THREAD

**Issue by Jayaramulu** [single-spa/single-spa-angularjs#65]
the below one is exact my requirement but here only used react and angular, but want know like how to include angularjs here

https://github.com/nitinreddy3/react-ng-spa-app

**Comment by joeldenning** [comment]
Just add a `registerApplication()` for your angularjs application to that example, and it will work. https://github.com/nitinreddy3/react-ng-spa-app/blob/main/root-config/src/org1-root-config.ts

Closing as this seems to be neither a bug report nor a question, but just a statement of what you want.
